language: php

php:
  - 7.1

before_script:
  - composer install --prefer-source --no-interaction

script:
  - phpunit --debug --coverage-clover=coverage.xml
  - php artisan dusk

after_success:
  - bash <(curl -s https://codecov.io/bash)

